version: '2'

networks:
  network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network
    links:
      - postgres
#      - elasticsearch
#    logging:
#      driver: awslogs
#      options:
#        awslogs-region: "us-east-1"
#        awslogs-group: "laravel"
#        awslogs-create-group: "true"
    environment:
        - APP_NAME=Laravel
        - APP_ENV=local
        - APP_DEBUG=false
        - APP_LOG_LEVEL=debug
        - APP_KEY=base64:/bWs7ShpstA3erE4KbSZjMgx0I09/9CTjozbWBaFWi4=
        - DB_CONNECTION=pgsql
        - DB_HOST=postgres
        - DB_DATABASE=laravel
        - DB_PORT=5432
        - DB_USERNAME=postgres
        - DB_PASSWORD=8hvpy2hS38
        - REDIS_HOST=redis
        - CACHE_DRIVER=file
        - QUEUE_DRIVER=sync
        - SESSION_DRIVER=redis
        - MAIL_DRIVER=smtp
        - MAIL_HOST=smtp.sendgrid.net
        - MAIL_PORT=587
        - MAIL_USERNAME=apikey
        - MAIL_PASSWORD=pwd
        - MAIL_FROM_ADDRESS=hello@laravel.info
        - MAIL_FROM_NAME=Admin
#        - ELASTICSEARCH_HOST=elasticsearch
#        - ELASTICSEARCH_PORT=9200
        - APP_URL=https://laravel.info
        - FILESYSTEM_DRIVER=s3
        - AWS_REGION=us-east-1
        - AWS_BUCKET=s3_bucket

#  elasticsearch:
#    image: elasticsearch:5.5
#    networks:
#      - network

#  cron:
#    build:
#      context: .
#      dockerfile: Dockerfile-cron
#    networks:
#      - network
#    environment:


  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network
    logging:
      driver: awslogs
      options:
        awslogs-region: "eu-east-1"
        awslogs-group: "nginx"
        awslogs-create-group: "true"
    links:
        - app

  postgres:
    image: postgres:9.6
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=laravel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8hvpy2hS38
    networks:
      - network

  redis:
    image: redis
    networks:
      - network

volumes:
  dbdata:
    driver: local

